services:
  catalogo-db:
    image: postgres:15-alpine
    container_name: catalogo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: contrasena_secreta
      POSTGRES_DB: catalogo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_compose:/var/lib/postgresql/data


volumes:
  pgdata_compose: