services:
  catalogo-db:
    image: postgres:15-alpine
    container_name: catalogo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: contrasena_secreta
      POSTGRES_DB: catalogo-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_catalogo:/var/lib/postgresql/data

  inventario-db:
    image: postgres:15-alpine
    container_name: inventario-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: contrasena_secreta
      POSTGRES_DB: inventario-db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_inventario:/var/lib/postgresql/data

  ventas-db:
    image: postgres:15-alpine
    container_name: ventas-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: contrasena_secreta
      POSTGRES_DB: ventas-db
    ports:
      - "5434:5432"
    volumes:
      - pgdata_ventas:/var/lib/postgresql/data

  usuarios-db:
    image: postgres:15-alpine
    container_name: usuarios-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: contrasena_secreta
      POSTGRES_DB: usuarios-db
    ports:
      - "5435:5432"
    volumes:
      - pgdata_usuarios:/var/lib/postgresql/data


volumes:
  pgdata_catalogo:
  pgdata_inventario:
  pgdata_ventas:
  pgdata_usuarios: