spring.application.name=servicio
grpc.server.port=9090
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/catalogo-db
spring.datasource.username=postgres
spring.datasource.password=contrasena_secreta

#spring.batch.jdbc.initialize-schema=always
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
