spring.application.name=servicio
grpc.port=9093
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5435/ventas-db
spring.datasource.username=postgres
spring.datasource.password=contrasena_secreta

#spring.batch.jdbc.initialize-schema=always
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Con esto desactivvo las validaciones automaticas. Las validaciones se realizan manualmente con un validator
spring.jpa.properties.jakarta.persistence.validation.mode=none

# Indica a Spring que siempre inicialice la base de datos usando scripts SQL
spring.sql.init.mode=always
# Hibernate crea las tablas ANTES de ejecutar schema.sql
spring.jpa.defer-datasource-initialization=true

# # Configuración del cliente gRPC para servicio de catálogo
# grpc.client.catalogo.host=localhost
# grpc.client.catalogo.port=9090

# # Configuración del cliente gRPC para servicio de inventario
# grpc.client.inventario.host=localhost
# grpc.client.inventario.port=9091


